server:
  port: 8888

#gateway:
#  ip:

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///SSAFY-workspace/00.MSA/MSA/git-local-repo
